POST http://localhost:8080/api/login
Content-Type: application/json

{
    "email": "testing123@test.com",
    "password": "testing123"
}

###
POST http://localhost:8080/api/signup
Content-Type: application/json

{
    "email": "testing123@test.com",
    "password": "testing123"
}

###

GET http://localhost:8080/user-profile HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZTkwODMzZTIxYjIxODJjYjhkY2VmOGMiLCJlbWFpbCI6InRlc3RpbmcxMjNAdGVzdC5jb20iLCJpYXQiOjE1ODY1NDYxNDh9.dp9LK1f5cH7cg_wMmDYHzM4T-4IBDS6HzzyT49dgIeI